
include $(top_srcdir)/config/makefile_templates/demo_drivers

# Name of executables: The prefix "noinst" means the executables don't
# have to be installed anywhere.
noinst_PROGRAMS = unrotated_square \
                  rotated_square \
                  rotated_square_upgraded \
                  circular_disc \
                  matthias_disk_explorer_fvk \
                  matthias_disk_explorer_ks \
                  matthias_mesh_checker \
                  hexagon \
                  circular_sector \
                  sector_corner_modes \
                  square_corner_modes \
                  star_trek \
                  triangular_plate \
                  axisym_displ_based_fvk \
                  element_test \
                  test_disk_fvk \
                  test_disk_restart_fvk \
                  test_disk_damped_fvk \
                  fvk_axisymmetric \
                  rupinder_fvk_axisymmetric \
                  find_wavenumber




#-Odd ones out---------------------------------------------------------
# Sources for axisym driver
rupinder_fvk_axisymmetric_SOURCES = rupinder_fvk_axisymmetric.cc 
find_wavenumber_SOURCES = find_wavenumber.cc

# Required libraries: 
rupinder_fvk_axisymmetric_LDADD = -L@libdir@ -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
find_wavenumber_LDADD = -L@libdir@ -lgeneric $(EXTERNAL_LIBS) $(FLIBS)




#-Odd ones out---------------------------------------------------------
# Sources for axisym driver
axisym_displ_based_fvk_SOURCES = axisym_displ_based_fvk.cc 
# Required libraries: 
axisym_displ_based_fvk_LDADD = -L@libdir@  -laxisym_displ_based_foeppl_von_karman -lgeneric $(EXTERNAL_LIBS) $(FLIBS)


#-FvK sources---------------------------------------------------------------
unrotated_square_SOURCES = \
 unrotated_square.cc
rotated_square_SOURCES = \
 rotated_square.cc
rotated_square_upgraded_SOURCES = \
 rotated_square_upgraded.cc
circular_disc_SOURCES = \
 circular_disc.cc
matthias_disk_explorer_fvk_SOURCES = \
 matthias_disk_explorer.cc
matthias_disk_explorer_ks_SOURCES = \
 matthias_disk_explorer.cc
matthias_mesh_checker_SOURCES = \
 matthias_mesh_checker.cc
hexagon_SOURCES = \
 hexagon.cc
circular_sector_SOURCES = \
 circular_sector.cc
sector_corner_modes_SOURCES = \
 sector_corner_modes.cc
square_corner_modes_SOURCES = \
 square_corner_modes.cc
triangular_plate_SOURCES = \
 triangular_plate.cc
star_trek_SOURCES = \
 star_trek.cc
element_test_SOURCES = \
 element_test.cc
 test_disk_fvk_SOURCES = \
 test_disk.cc
 test_disk_restart_fvk_SOURCES = \
 test_disk_restart.cc
  test_disk_damped_fvk_SOURCES = \
 test_disk_damped.cc
 fvk_axisymmetric_SOURCES = \
 fvk_axisymmetric.cc
 
matthias_disk_explorer_ks_CXXFLAGS = -DUSE_KS




#-FvK libraries-------------------------------------------------------------
unrotated_square_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
rotated_square_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
rotated_square_upgraded_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
circular_disc_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
matthias_disk_explorer_fvk_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
matthias_disk_explorer_ks_LDADD = -L@libdir@ -lc1_koiter_steigmann \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
matthias_mesh_checker_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
hexagon_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
circular_sector_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
sector_corner_modes_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
square_corner_modes_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
triangular_plate_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
star_trek_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
element_test_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
test_disk_fvk_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
 test_disk_restart_fvk_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
  test_disk_damped_fvk_LDADD = -L@libdir@ -lc1_foeppl_von_karman \
 -lgeneric $(EXTERNAL_LIBS) $(FLIBS)
fvk_axisymmetric_LDADD = -L@libdir@ -lgeneric $(EXTERNAL_LIBS) $(FLIBS) 


# Local sources that Jack's own code depends on: This code also uses
# objects from Jack's own library. The source code for this library
# lives in user_src/jack_cool and gets compiled in to the jack_cool 
# library. If we use it, we have to link against it...
#jacks_own_code_SOURCES = jacks_own_code.cc

# Required libraries: Jack's own library ("jack_cool") and oomph-lib's 
# and "generic" and "poisson" libraries. Following the logic
# explained above, Jack's own library should go first since it may
# (or may not) depend on objects in the other libraries, whereas they will
# certainly not depend on objects in his. 
# jacks_own_code_LDADD = -L@libdir@ -ljack_cool -lpoisson -lgeneric $(EXTERNAL_LIBS) $(FLIBS)

#---------------------------------------------------------------------------


# Include path for library headers: All library headers live in 
# the include directory which we specify with -I
# Automake will replace the variable @includedir@ with the actual
# include directory.

AM_CPPFLAGS += -I@includedir@ -Wall -ggdb3 -O0
#EXTRA_DIST = Circle1.1.ele Circle1.1.node Circle1.1.poly
